language: python

python:
  - "2.5"
  - "2.6"
  - "2.7"

env:
  - DJANGO=Django==1.3.7
  - DJANGO=Django==1.4.5
  - DJANGO=Django==1.5
  - DJANGO=https://github.com/django/django/tarball/master

matrix:
  exclude:
    - env: DJANGO=Django==1.5
      python: "2.5"
    - env: DJANGO=https://github.com/django/django/tarball/master
      python: "2.5"
  allow_failures:
    - env: DJANGO=https://github.com/django/django/tarball/master

install:
  - "pip install -q $DJANGO --use-mirrors"
  - "pip install argparse"
  - "pip install pep8"
  - "python setup.py install"

before_script:
  - "pep8 --ignore=E128,E501,W293 pehg"

script:
  - "python runtests.py --no-coverage"
  
notifications:
  email: false
